### ISSUE TITLE
space-x-4 does not work

### ISSUE THREAD

**Issue by tcosmo** [oekazuma/sveltekit-typescript-windicss#1]
Tailwind class such as `space-x-4` does not seem to work.

Example:

```html
<div class="w-full flex space-x-4">
  <div>hey</div>
  <div>how</div>
  <div>are</div>
  <div>you</div>
</div>
```

**Comment by oekazuma** [comment]
It seems to work fine as far as I have tried.

Make sure you are not using an older version.

**Comment by tcosmo** [comment]
Weird... This particular CSS class does not appear in the compiled CSS for me. I cloned the repo earlier today.

**Comment by oekazuma** [comment]
I can confirm that it is working fine both locally and on [Gitpod](https://gitpod.io/#https://github.com/oekazuma/sveltekit-typescript-windicss)...

Sorry, I can't help you as I don't know your environment.

**Comment by tcosmo** [comment]
Ah! Something weird is that I have the bug ONLY in the file `__layout.svelte`

Have the following html in `__layout.svelte`:

```html
<div class="p-3">
  <div class="w-1/2 bg-red-500 flex space-x-5">
		  <div>Hey</div>
		  <div>Hey</div>
		  <div>Hey</div>
		  <div>Hey</div>
  </div>
  <slot />
</div>
```
And the following in `index.svelte`:

```html
<div class="w-1/2 bg-red-400 flex space-x-5">
	<div>Hey</div>
	<div>Hey</div>
	<div>Hey</div>
	<div>Hey</div>
</div>
```

I get the following result:

![Screenshot 2022-03-05 at 17 23 19](https://user-images.githubusercontent.com/7616128/156893611-def47261-7250-4cdd-9872-5257b76a1b9f.png)

My environment is:

```
macos 11.6
Chrome 98
yarn 1.22.11
```

**Comment by tcosmo** [comment]
Ah again!

Note that in `__layout.svelte` I have the following code:

```html
<style global windi:global windi:preflights:global windi:safelist:global>
	body {
		@apply bg-gray-900 text-white font-mono;
	}

	a {
		@apply cursor-pointer;
	}

	a:hover {
		@apply text-gray-200;
	}
</style>
```

The `space-x-4` bug goes away if I remove the keyword `global`. But I put it there otherwise the CSS doesnt apply to `body`.

Would you have any clue?

**Comment by oekazuma** [comment]
This is odd...  It may be a bug.
Why don't you try opening an issue in [svelte-windicss-preprocess](https://github.com/windicss/svelte-windicss-preprocess)?

In the meantime, the following appears to be a workaround!

`_layout.svelte`
```svelte
<div class="p-3">
  <div class="w-1/2 bg-red-500 flex space-x-5">
    <div>Hey</div>
    <div>Hey</div>
    <div>Hey</div>
    <div>Hey</div>
  </div>
  <slot />
</div>

<style windi:global windi:preflights:global windi:safelist:global>
    :global(body) {
		@apply bg-gray-900 text-white font-mono;
	}

    :global(a) {
		@apply cursor-pointer;
	}

    :global(a):hover {
		@apply text-gray-200;
	}
</style>
```

**Comment by tcosmo** [comment]
Really cool thank you very much!

**Comment by oekazuma** [comment]
This issue is closed because it is a svelte-windicss-preprocess issue.
